server:
  port: ${PORT:0}

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cartdb
    username: root
    password: '7781'
  
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
	globally_quoted_identifiers: true
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
  sql:
    init:
      mode: always
      platform: sql

configuration:
    texto: Configurando entorno Desarrollo ...
    autor:
        nombre: John Doe
        email: johndoe@email.com